### ISSUE TITLE
Issues with running backend

### ISSUE THREAD

**Issue by adamstep** [rkv5019/TeamMembersFullStack#1]
Hello,

I tried to install the app following the README and got this error when starting the backend:

```
ModuleNotFoundError: No module named 'rest_framework_simplejwt'
```

Please let me know when this is fixed so I can test the app, thanks!

**Comment by rkv5019** [comment]
Hey!

Sorry about that, I was playing around with JWT tokens and had an unused import I accidentally left in.

I removed it and you should be good to go now. I also added additional steps for PostgreSQL setup if needed.

Thanks!
